### PR TITLE
Fix integration tests

### LINKED ISSUE #244: Fix `mage test:integration`
currently failing, config doesn't start the executable

### PR DESCRIPTION
**Pull request by leehinman**
## What does this PR do?

updates integration tests to work with changes brought in with v2 protocol

- switched to configuration layout mandated by v2
- added `mage test` target that will run both unit and integration tests
- switched CI runs from just running unit tests to running all tests
- Skipped integration tests that require docker to run logstash or kafka, support for doing that is finalized in magefile.
- updated example config file

## Why is it important?

we need integration tests :-)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.md` or `CHANGELOG-developer.md`.

## How to test this PR locally

``` sh
mage test
```

## Related issues

- Closes #244

### CODE REVIEW

**Review by faec — APPROVED** [review]

File: controller/run_test.go [hunk 1]
```diff
@@ -45,21 +44,16 @@ func TestUnmanaged(t *testing.T) {
 		default:
 		}
 		_, err := os.Stat(serverAddr)
-		if !os.IsNotExist(err) {
-			break
+		if err != nil && errors.Is(err, fs.ErrNotExist) {
+			continue
 		}
+		con, err := net.Dial("unix", serverAddr)
```
Comment (fearful-symmetry) [inline controller/run_test.go:50]: Now that I think of it, if we're going to run the `dial` call in a loop, is the `os.Stat` needed? if there's an issue with the file, it will get caught by the `Dial` call.

Comment (leehinman) [reply controller/run_test.go:50]: yeah, this can be simplified.  I'll do a last pass once it all works on Unix, Mac & Windows.

**Comment by fearful-symmetry** [comment]
Alright, tested locally:
```
DONE 34 tests, 4 skipped in 10.808s
>> go test: Integration Tests : Test Passed
```
It looks like some of those skipped tests are just marked as `SkipNow()`. Are they still in development?
